name: Build and Test

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  release:
    types: [created, published]
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 1.0.0)'
        required: false
        default: 'manual-build'
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      build_type:
        description: 'Build type'
        required: false
        default: 'debug'
        type: choice
        options:
          - 'debug'
          - 'release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        if: github.event.inputs.skip_tests != 'true'
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            ./gradlew testReleaseUnitTest
          else
            ./gradlew testDebugUnitTest
          fi

      - name: Run instrumented tests
        if: github.event.inputs.skip_tests != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.sha }}
          path: |
            app/build/reports/tests/
            app/build/test-results/
          retention-days: 30

      - name: Determine build type
        id: build-type
        run: |
          # Release builds: tags or manual release selection
          if [[ "${{ github.ref }}" == refs/tags/* ]] || [[ "${{ github.event.inputs.build_type }}" == "release" ]]; then
            echo "type=release" >> $GITHUB_OUTPUT
            echo "Building RELEASE APK"
          else
            echo "type=debug" >> $GITHUB_OUTPUT
            echo "Building DEBUG APK"
          fi

      - name: Decode keystore
        if: steps.build-type.outputs.type == 'release'
        run: |
          if [ -n "${{ secrets.KEYSTORE_FILE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 -d > release.keystore
          fi

      - name: Build APK
        env:
          KEYSTORE_FILE: release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          if [[ "${{ steps.build-type.outputs.type }}" == "release" ]] && [ -f "release.keystore" ]; then
            echo "Building signed release APK"
            ./gradlew assembleRelease
          else
            echo "Building debug APK"
            ./gradlew assembleDebug
          fi

      - name: Determine version name
        id: version
        run: |
          if [ -n "${{ github.event.inputs.version_name }}" ]; then
            VERSION="${{ github.event.inputs.version_name }}"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="nightly-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "name=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Rename APK
        run: |
          VERSION="${{ steps.version.outputs.name }}"

          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
            mv app/build/outputs/apk/release/app-release.apk app-${VERSION}.apk
            echo "Created: app-${VERSION}.apk"
          elif [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            mv app/build/outputs/apk/debug/app-debug.apk app-${VERSION}-debug.apk
            echo "Created: app-${VERSION}-debug.apk"
          fi

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ steps.version.outputs.name }}
          path: app-*.apk
          retention-days: ${{ startsWith(github.ref, 'refs/tags/') && 90 || 30 }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: app-*.apk
          tag_name: ${{ steps.version.outputs.name }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build summary
        run: |
          echo "✓ Build completed successfully"
          echo "  Version: ${{ steps.version.outputs.name }}"
          echo "  Build type: ${{ steps.build-type.outputs.type }}"
          echo "  Commit: ${{ github.sha }}"
          echo "  Branch/Tag: ${{ github.ref_name }}"
          echo ""
          echo "APK files:"
          ls -lh app-*.apk 2>/dev/null || echo "No renamed APK found"
          ls -lh app/build/outputs/apk/*/*.apk 2>/dev/null || echo "No APK in build directory"

